import { ClubStats } from '@/types/football';

export const INITIAL_CLUBS: Omit<ClubStats, 'id'>[] = [
  // Grupo 1
  { name: 'Racing Club Ferrol', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CF Talavera de la Reina', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Arenas Club', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CD Arenteiro', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Real Avilés Industrial', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'SD Ponferradina', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CD Guadalajara', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CD Tenerife', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Real Madrid Castilla', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CD Lugo', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Zamora CF', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'RC Celta Fortuna', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Ourense CF', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Athletic Club B', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'AD Mérida', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Barakaldo CF', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Unionistas de Salamanca', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CA Osasuna B', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Pontevedra CF', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CP Cacereño', group: 1, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  
  // Grupo 2
  { name: 'Atlético Madrileño', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Atlético Sanluqueño', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Hércules CF', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'SD Tarazona', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Marbella FC', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Real Murcia CF', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Antequera CF', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'FC Cartagena', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Villarreal CF B', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'AD Alcorcón', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CE Sabadell', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CD Eldense', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Sevilla Atlético', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'UD Ibiza', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Juventud de Torremolinos', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CE Europa', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Gimnàstic de Tarragona', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Algeciras CF', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'CD Teruel', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  { name: 'Betis Deportivo Balompié', group: 2, goalsScored: { home: [], away: [] }, goalsConceded: { home: [], away: [] }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
];
